version: '3.9'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      POSTGRES_DSN: "host=db user=gorm password=gorm dbname=hefesto port=5432 sslmode=disable"
      API_KEY: "JzNztV4A"
      MONGODB_URI: "mongodb://vault:27017"
      MONGODB_MOOD_COLLECTION: "moodVault"
      MONGODB_POSTS_COLLECTION: "postsVault"
    depends_on:
      - db

  db:
    build: config/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "gorm"
    volumes:
      - pgdata:/var/lib/postgresql/data

  vault:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/var/lib/mongodb/data

volumes:
  pgdata:
  mongodata: